(() => {
  'use strict';
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],api=window.EditorV5,config=api.getConfig();
  config.schemaVersion=5;
  config.titleScreen.frameStyle={shape:'rounded',borderWidth:3,radius:23,glowEnabled:true,...config.titleScreen.frameStyle};
  config.helper.bubbleStyle={shape:'speech',backgroundColor:'#ffffff',backgroundImage:null,backgroundFit:'cover',overlay:0,borderColor:'#7968ef',borderWidth:3,radius:18,textColor:'#182033',textSize:15,glowColor:'#806dff',glowIntensity:12,...config.helper.bubbleStyle};
  config.helper.skipStyle={backgroundColor:'#e9e7ff',textColor:'#5749bd',borderColor:'#7968ef',borderWidth:0,radius:7,glowColor:'#806dff',...config.helper.skipStyle};
  config.helper.bubbleStyle.width??=47;config.helper.bubbleStyle.padding??=11;
  config.crosshair={type:'classic',size:72,width:3,color:'#ffffff',glow:'#000000',...config.crosshair};
  config.hud={backgroundColor:'#11172d',backgroundOpacity:82,borderColor:'#ffffff',borderWidth:1,radius:14,textColor:'#ffffff',fontSize:15,gap:8,paddingX:10,paddingY:7,glowColor:'#000000',glowIntensity:10,...config.hud};
  config.taskTheme={backgroundColor:'#ffffff',backgroundOpacity:96,backgroundImage:null,backgroundFit:'cover',borderColor:'#9a8cff',borderWidth:3,radius:23,glowColor:'#7968ef',glowIntensity:20,questionColor:'#182033',questionFontSize:28,answerTextColor:'#182033',answerFontSize:18,answerBackgroundColor:'#edf0f7',answerBorderColor:'#d9deea',selectedAnswerColor:'#7968ef',correctAnswerColor:'#25b875',wrongAnswerColor:'#e84f62',spacing:8,...config.taskTheme};
  config.taskTheme.checkButton={backgroundColor:'#7968ef',textColor:'#ffffff',borderColor:'#5d50c8',glowColor:'#7968ef',glowIntensity:12,...config.taskTheme.checkButton};
  let previewState={screen:'game',mode:'edit'},restoreQueued=false;
  const hideLayers=()=>{$('#titleScreen').hidden=true;$('#taskModal').hidden=true;$('#resultScreen').hidden=true;$('#roundIntroScreen').hidden=true;$('#helper').className='helper'};
  const activate=key=>$$('[data-preview]').forEach(b=>b.classList.toggle('active',b.dataset.preview===key));
  function showRound(auto=false){hideLayers();const c=$('#roundIntroCard'),n=($('#roundValue').textContent||'1').split('/')[0].trim();c.textContent=($('#roundIntroText').value||'Раунд {n}').replace('{n}',n);c.style.background=$('#roundIntroBg').value;c.style.borderColor=$('#roundIntroFrame').value;c.className=`round-intro-card anim-${$('#roundIntroAnimation').value}`;$('#roundIntroScreen').hidden=false;if(auto)setTimeout(()=>$('#roundIntroScreen').hidden=true,Math.max(.5,+$('#roundIntroDuration').value||2)*1000)}
  function showTask(){hideLayers();const task=config.tasks?.[0];$('#taskTypeLabel').textContent='ПРИМЕР ЗАДАНИЯ';$('#modalQuestion').innerHTML=api.math(task?.question||'Чему равно $\\frac{1}{2}+x^2$?');$('#answerArea').innerHTML=(task?.answers?.length?task.answers:[{text:'Ответ 1'},{text:'Ответ 2'}]).map((a,i)=>`<label class="answer-option"><input type="radio" name="preview-v5" ${i?'':'checked'}><span>${api.math(a.text)}</span></label>`).join('');$('#taskModal').hidden=false}
  function display(key=previewState.screen){previewState.screen=key;window.__editorPreviewScreen=key;activate(key);hideLayers();if(key==='title')$('#titleScreen').hidden=false;else if(key==='helper')$('#helper').className='helper visible enter-rise';else if(key==='round')showRound();else if(key==='task')showTask();else if(['victory','defeat','timeout'].includes(key))api.showResult(key,true);applyTheme()}
  function queueRestore(){if(restoreQueued)return;restoreQueued=true;queueMicrotask(()=>{restoreQueued=false;if(previewState.mode==='edit')display()})}
  $$('[data-preview]').forEach(b=>b.onclick=()=>display(b.dataset.preview));document.addEventListener('input',queueRestore);document.addEventListener('change',queueRestore);
  const oldToggle=$('#toggleTest').onclick;$('#toggleTest').onclick=e=>{previewState.mode=previewState.mode==='edit'?'play':'edit';oldToggle?.call(e.currentTarget,e);if(previewState.mode==='edit')display()};
  const oldRestart=$('#restartGame').onclick;$('#restartGame').onclick=e=>{previewState.mode='play';oldRestart?.call(e.currentTarget,e)};
  const oldSkip=$('#skipHelper').onclick;$('#skipHelper').onclick=e=>{oldSkip?.call(e.currentTarget,e);setTimeout(()=>showRound(true),460)};
  const bindings={
    v5TitleShape:['titleScreen','frameStyle','shape'],v5TitleBorderWidth:['titleScreen','frameStyle','borderWidth'],v5TitleRadius:['titleScreen','frameStyle','radius'],v5TitleGlowEnabled:['titleScreen','frameStyle','glowEnabled'],
    v5HelperShape:['helper','bubbleStyle','shape'],v5HelperBg:['helper','bubbleStyle','backgroundColor'],v6HelperWidth:['helper','bubbleStyle','width'],v6HelperPadding:['helper','bubbleStyle','padding'],v5HelperTextColor:['helper','bubbleStyle','textColor'],v5HelperBorder:['helper','bubbleStyle','borderColor'],v5HelperBorderWidth:['helper','bubbleStyle','borderWidth'],v5HelperTextSize:['helper','bubbleStyle','textSize'],v5HelperRadius:['helper','bubbleStyle','radius'],v5HelperGlow:['helper','bubbleStyle','glowColor'],v5HelperGlowSize:['helper','bubbleStyle','glowIntensity'],v5HelperBgFit:['helper','bubbleStyle','backgroundFit'],v5HelperOverlay:['helper','bubbleStyle','overlay'],
    v5SkipBg:['helper','skipStyle','backgroundColor'],v5SkipText:['helper','skipStyle','textColor'],v5SkipBorder:['helper','skipStyle','borderColor'],v5SkipBorderWidth:['helper','skipStyle','borderWidth'],v5SkipRadius:['helper','skipStyle','radius'],v5SkipGlow:['helper','skipStyle','glowColor'],
    v5HudBg:['hud','backgroundColor'],v5HudOpacity:['hud','backgroundOpacity'],v5HudBorder:['hud','borderColor'],v5HudBorderWidth:['hud','borderWidth'],v5HudRadius:['hud','radius'],v5HudText:['hud','textColor'],v5HudFontSize:['hud','fontSize'],v5HudGap:['hud','gap'],v5HudPaddingX:['hud','paddingX'],v5HudPaddingY:['hud','paddingY'],v5HudGlow:['hud','glowColor'],v5HudGlowSize:['hud','glowIntensity'],
    v5TaskBg:['taskTheme','backgroundColor'],v5TaskOpacity:['taskTheme','backgroundOpacity'],v5TaskBorder:['taskTheme','borderColor'],v5TaskBorderWidth:['taskTheme','borderWidth'],v5TaskRadius:['taskTheme','radius'],v5TaskGlow:['taskTheme','glowColor'],v5TaskGlowSize:['taskTheme','glowIntensity'],v5TaskSpacing:['taskTheme','spacing'],v5QuestionSize:['taskTheme','questionFontSize'],v5QuestionColor:['taskTheme','questionColor'],v5AnswerSize:['taskTheme','answerFontSize'],v5AnswerColor:['taskTheme','answerTextColor'],v5AnswerBg:['taskTheme','answerBackgroundColor'],v5AnswerBorder:['taskTheme','answerBorderColor'],v5AnswerSelected:['taskTheme','selectedAnswerColor'],v5AnswerCorrect:['taskTheme','correctAnswerColor'],v5AnswerWrong:['taskTheme','wrongAnswerColor'],v6CheckBg:['taskTheme','checkButton','backgroundColor'],v6CheckText:['taskTheme','checkButton','textColor'],v6CheckBorder:['taskTheme','checkButton','borderColor'],v6CheckGlow:['taskTheme','checkButton','glowColor'],v6CheckGlowSize:['taskTheme','checkButton','glowIntensity'],v6CrosshairSize:['crosshair','size'],v6CrosshairWidth:['crosshair','width'],v6CrosshairColor:['crosshair','color'],v6CrosshairGlow:['crosshair','glow']};
  const get=p=>p.reduce((o,k)=>o[k],config),set=(p,v)=>{let o=config;for(let i=0;i<p.length-1;i++)o=o[p[i]];o[p.at(-1)]=v};
  for(const[id,path]of Object.entries(bindings)){const el=$('#'+id);if(!el)continue;const value=get(path);if(el.type==='checkbox')el.checked=!!value;else el.value=value;const output=el.parentElement?.querySelector('output');if(output)output.textContent=value;el.addEventListener(el.tagName==='SELECT'||el.type==='checkbox'?'change':'input',()=>{let v=el.type==='checkbox'?el.checked:el.value;if(el.type==='range'||el.type==='number')v=+v;set(path,v);if(output)output.textContent=v;api.applyConfig();applyTheme()})}
  $$('[data-crosshair]').forEach(button=>{button.classList.toggle('active',button.dataset.crosshair===config.crosshair.type);button.onclick=()=>{config.crosshair.type=button.dataset.crosshair;$$('[data-crosshair]').forEach(x=>x.classList.toggle('active',x===button));api.applyConfig();applyTheme()}});
  function alpha(hex,opacity){const h=hex.replace('#','');return `rgba(${parseInt(h.slice(0,2),16)},${parseInt(h.slice(2,4),16)},${parseInt(h.slice(4,6),16)},${opacity/100})`}
  function shape(el,kind,radius){el.classList.remove(...[...el.classList].filter(x=>x.startsWith('shape-')));el.classList.add('shape-'+kind);el.style.borderRadius=kind==='rectangle'?'0':kind==='pill'?'999px':radius+'px'}
  function applyTheme(){
    const ts=config.titleScreen.frameStyle,card=$('#titleCard');shape(card,ts.shape,ts.radius);card.style.borderWidth=ts.borderWidth+'px';card.style.boxShadow=ts.glowEnabled?`0 0 ${config.titleScreen.glowSize}px ${config.titleScreen.glow}`:'none';
    const hb=config.helper.bubbleStyle,bubble=$('.helper-dialog');shape(bubble,hb.shape,hb.radius);bubble.style.cssText+=`;width:${hb.width}%;max-width:${hb.width}%;padding:${hb.padding}px;color:${hb.textColor};font-size:${hb.textSize}px;border:${hb.borderWidth}px solid ${hb.borderColor};box-shadow:0 0 ${hb.glowIntensity}px ${hb.glowColor};background-image:${hb.backgroundImage?`linear-gradient(rgba(0,0,0,${hb.overlay/100}),rgba(0,0,0,${hb.overlay/100})),url("${hb.backgroundImage}")`:'none'};background-color:${hb.backgroundColor};background-position:center;background-size:${hb.backgroundFit};background-repeat:no-repeat`;
    const sk=config.helper.skipStyle,skip=$('#skipHelper');skip.style.cssText=`background:${sk.backgroundColor};color:${sk.textColor};border:${sk.borderWidth}px solid ${sk.borderColor};border-radius:${sk.radius}px;box-shadow:0 0 12px ${sk.glowColor}`;
    const h=config.hud,hud=$('.hud');hud.style.cssText=`--hud-bg:${alpha(h.backgroundColor,h.backgroundOpacity)};--hud-border:${h.borderColor};--hud-text:${h.textColor};--hud-font:${h.fontSize}px;--hud-gap:${h.gap}px;--hud-px:${h.paddingX}px;--hud-py:${h.paddingY}px;--hud-radius:${h.radius}px;--hud-bw:${h.borderWidth}px;--hud-shadow:0 0 ${h.glowIntensity}px ${h.glowColor}`;
    const t=config.taskTheme,tc=$('#taskCard');tc.style.cssText=`background:${t.backgroundImage?`linear-gradient(rgba(255,255,255,${t.backgroundOpacity/100}),rgba(255,255,255,${t.backgroundOpacity/100})),url("${t.backgroundImage}") center/${t.backgroundFit} no-repeat`:alpha(t.backgroundColor,t.backgroundOpacity)};border:${t.borderWidth}px solid ${t.borderColor};border-radius:${t.radius}px;box-shadow:0 0 ${t.glowIntensity}px ${t.glowColor};--q:${t.questionFontSize}px;--a:${t.answerFontSize}px;--task-q:${t.questionColor};--answer-text:${t.answerTextColor};--answer-bg:${t.answerBackgroundColor};--answer-border:${t.answerBorderColor};--answer-selected:${t.selectedAnswerColor};--answer-ok:${t.correctAnswerColor};--answer-bad:${t.wrongAnswerColor};--answer-gap:${t.spacing}px`;
    const cb=t.checkButton,check=$('#checkAnswer');check.style.cssText=`background:${cb.backgroundColor};color:${cb.textColor};border:2px solid ${cb.borderColor};box-shadow:0 0 ${cb.glowIntensity}px ${cb.glowColor}`;
    $('#livesHud').style.setProperty('font-size',config.rules.livesSize+'px','important');const ch=config.crosshair,cross=$('#crosshair');cross.className='crosshair '+ch.type;cross.style.cssText=`--cross-size:${ch.size}px;--cross-width:${ch.width}px;--cross:${ch.color};filter:drop-shadow(0 0 7px ${ch.glow})`;
  }
  async function image(file,maxW,maxH){if(!file||!file.type.startsWith('image/')||file.size>15e6)throw Error('Выберите изображение до 15 МБ');const url=URL.createObjectURL(file),img=new Image();img.src=url;await img.decode();const scale=Math.min(1,maxW/img.width,maxH/img.height),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);return canvas.toDataURL('image/webp',.8)}
  async function compressData(src){if(!/^data:image\//.test(src))return src;const img=new Image();img.src=src;await img.decode();const scale=Math.min(1,1280/img.width,720/img.height),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/webp',.55)}
  async function lightenObject(root){let count=0;for(const key of Object.keys(root||{})){const value=root[key];if(typeof value==='string'&&value.startsWith('data:image/')){root[key]=await compressData(value);count++}else if(value&&typeof value==='object')count+=await lightenObject(value)}return count}
  $('#lightenProject').onclick=async()=>{const button=$('#lightenProject');button.disabled=true;button.classList.remove('code-lightened','code-lighten-error');button.textContent='Сжатие…';try{await lightenObject(config);api.applyConfig();applyTheme();display();button.classList.add('code-lightened');button.textContent='✓ Код облегчён'}catch{button.classList.add('code-lighten-error');button.textContent='Ошибка сжатия'}finally{button.disabled=false}};
  async function upload(input,path,w=1200,h=800){const file=input.files?.[0];if(!file)return;try{const data=await image(file,w,h);set(path,data);api.applyConfig();applyTheme();display()}catch(e){alert(e.message)}finally{input.value=''}}
  $('#v5HelperBgUpload').onchange=e=>upload(e.target,['helper','bubbleStyle','backgroundImage']);$('#v5TaskBgUpload').onchange=e=>upload(e.target,['taskTheme','backgroundImage']);$('#v5HelperBgDelete').onclick=()=>{config.helper.bubbleStyle.backgroundImage=null;api.applyConfig();applyTheme()};$('#v5TaskBgDelete').onclick=()=>{config.taskTheme.backgroundImage=null;api.applyConfig();applyTheme()};
  function enhanceScreens(){const root=$('#screenEditor');root.classList.add('screen-settings');$$('label',root).forEach(x=>x.classList.add('field-group'));const key=document.querySelector('[data-screen].active')?.dataset.screen||'victory',s=config.screens?.[key];if(!s||$('#v5ScreenExtras'))return;const box=document.createElement('div');box.id='v5ScreenExtras';box.className='subcard field-group';box.innerHTML='<h3>Типографика, свечение и анимация</h3><div class="grid2"><label>Размер заголовка<input id="v5ScreenTitleSize" type="range" min="22" max="72"></label><label>Свечение<input id="v5ScreenGlow" type="color"></label><label>Анимация<select id="v5ScreenAnimation"><option value="zoom">Приближение</option><option value="fade">Проявление</option><option value="rise">Снизу</option></select></label></div>';root.append(box);s.titleSize??=48;s.animation??='zoom';$('#v5ScreenTitleSize').value=s.titleSize;$('#v5ScreenGlow').value=s.glowColor;$('#v5ScreenAnimation').value=s.animation;$('#v5ScreenTitleSize').oninput=e=>{s.titleSize=+e.target.value;$('#resultTitle').style.fontSize=s.titleSize+'px';api.applyConfig()};$('#v5ScreenGlow').oninput=e=>{s.glowColor=e.target.value;api.showResult(key,true);api.applyConfig()};$('#v5ScreenAnimation').onchange=e=>{s.animation=e.target.value;api.applyConfig()}}
  $$('[data-screen]').forEach(b=>b.addEventListener('click',()=>queueMicrotask(()=>{enhanceScreens();previewState.screen=b.dataset.screen;display()})));enhanceScreens();
  config.publicGameUrl??='';$('#v5PublicGameUrl').value=config.publicGameUrl;$('#v5PublicGameUrl').oninput=e=>{config.publicGameUrl=e.target.value.trim();api.applyConfig()};$('#v5CopyPublicEmbed').onclick=async()=>{const url=config.publicGameUrl;if(!/^https:\/\//i.test(url)){alert('Укажите публичный адрес, начинающийся с https://');return}const code=`<div style="position:relative;width:100%;max-width:100%;aspect-ratio:16\/9;overflow:hidden"><iframe src="${url.replace(/"/g,'&quot;')}" title="Меткий ответ" style="position:absolute;inset:0;width:100%;height:100%;border:0" allow="autoplay; fullscreen" allowfullscreen></iframe></div>`;try{await navigator.clipboard.writeText(code);$('#v5CopyPublicEmbed').textContent='✓ Код скопирован';setTimeout(()=>$('#v5CopyPublicEmbed').textContent='Скопировать iframe с URL',1800)}catch{alert('Браузер запретил копирование')}};
  $('#projectFile').addEventListener('change',()=>setTimeout(()=>{config.helper.bubbleStyle={shape:'speech',backgroundColor:'#ffffff',backgroundImage:null,backgroundFit:'cover',overlay:0,borderColor:'#7968ef',borderWidth:3,radius:18,textColor:'#182033',textSize:15,width:47,padding:11,glowColor:'#806dff',glowIntensity:12,...config.helper.bubbleStyle};config.crosshair={type:'classic',size:72,width:3,color:'#ffffff',glow:'#000000',...config.crosshair};config.taskTheme??={};config.taskTheme.checkButton={backgroundColor:'#7968ef',textColor:'#ffffff',borderColor:'#5d50c8',glowColor:'#7968ef',glowIntensity:12,...config.taskTheme.checkButton};for(const[id,path]of Object.entries(bindings)){const el=$('#'+id),value=get(path);if(!el||value==null)continue;if(el.type==='checkbox')el.checked=!!value;else el.value=value;const out=el.parentElement?.querySelector('output');if(out)out.textContent=value}$$('[data-crosshair]').forEach(x=>x.classList.toggle('active',x.dataset.crosshair===config.crosshair.type));applyTheme();display();api.applyConfig()},350));
  const originalExport=$('#exportHtml').onclick;$('#copyGenially').onclick=async()=>{let blob;const make=URL.createObjectURL,click=HTMLAnchorElement.prototype.click;URL.createObjectURL=b=>(blob=b,'blob:preview');HTMLAnchorElement.prototype.click=()=>{};try{originalExport?.()}finally{URL.createObjectURL=make;HTMLAnchorElement.prototype.click=click}if(!blob)return;const html=await blob.text(),required=['game-stage','titleScreen','helper','taskModal','timerHud','resultScreen'];if(required.some(x=>!html.includes(x))||/(localhost|127\.0\.0\.1|node_modules|\/src\/)/.test(html)){alert('Экспорт не прошёл проверку целостности');return}const bytes=new TextEncoder().encode(html);let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));const code=`<div style="position:relative;width:100%;max-width:100%;aspect-ratio:16\/9;overflow:hidden"><iframe src="data:text/html;base64,${btoa(binary)}" title="Меткий ответ" style="position:absolute;inset:0;width:100%;height:100%;border:0" allow="autoplay; fullscreen" allowfullscreen></iframe></div>`;try{await navigator.clipboard.writeText(code);$('#copyGenially').textContent='✓ Код скопирован';setTimeout(()=>$('#copyGenially').textContent='Код Genially',1800)}catch{alert('Браузер запретил копирование')}};
  window.runV5PreviewStabilityTest=async()=>{const screens=['title','helper','round','task','victory','defeat','timeout'],results={};for(const screen of screens){display(screen);const before=previewState.screen,field=screen==='title'?$('#titleText'):screen==='helper'?$('#helperRules'):screen==='task'?$('#v5QuestionSize'):null,old=field?.value;if(field){for(let i=0;i<30;i++){field.value=field.type==='range'?18+i%20:`V5 test ${i}`;field.dispatchEvent(new Event('input',{bubbles:true}))}await Promise.resolve();field.value=old;field.dispatchEvent(new Event('input',{bubbles:true}))}results[screen]=previewState.screen===before&&$(`[data-preview="${screen}"]`).classList.contains('active')}display('game');return results};
  const copyEmbeddedGenially=$('#copyGenially').onclick;$('#copyGenially').onclick=()=>/^https:\/\//i.test(config.publicGameUrl)?$('#v5CopyPublicEmbed').click():copyEmbeddedGenially();
  applyTheme();display('game');api.applyConfig();
})();
